[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "shared",
    "admin_api",
    "frontend_api"
]
testpaths = ["tests"]
python_files = ["test_*.py"]
